"""empty message

Revision ID: dc793cb269d7
Revises: 5afe84c1818b
Create Date: 2020-11-03 13:00:54.576209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc793cb269d7'
down_revision = '5afe84c1818b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.String(length=64), nullable=False))
    op.add_column('user', sa.Column('job', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('password', sa.String(length=256), nullable=False))
    op.add_column('user', sa.Column('role', sa.SmallInteger(), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'role')
    op.drop_column('user', 'password')
    op.drop_column('user', 'job')
    op.drop_column('user', 'email')
    # ### end Alembic commands ###
